services:
  jira:
    image: myjira:latest
    container_name: jira
    restart: unless-stopped
    ports:
      - "8000:8080"
    volumes:
      - New_jira_data:/var/atlassian/application-data/jira
      - ./server.xml:/opt/atlassian/jira/conf/server.xml:ro
      - ./hosts:/etc/hosts:ro  
    environment:
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/jiradb
      - ATL_JDBC_USER=jiradbuser
      - ATL_JDBC_PASSWORD=mojtaba1369
      - ATL_DB_TYPE=postgres72
      - ATL_JIRA_HOME=/var/atlassian/application-data/jira

    networks:
      - jira-network
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: jira_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jiradb
      POSTGRES_USER: jiradbuser
      POSTGRES_PASSWORD: mojtaba1369
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - New_postgres_data:/var/lib/postgresql/data
    networks:
      - jira-network

volumes:
  New_jira_data:
    external: true
  New_postgres_data:
    external: true

networks:
  jira-network:
  #  external: true

